### ISSUE TITLE
Empty space on UI

### ISSUE THREAD

**Issue by fcana** [ramiro-uziel/FlexASIO-Fluent#4]
Hi,
first thank a lot for this wonderful project! The refresh button that finally works is stunning!
I'd like to report a *tiny* strange thing on UI for maybe future improvements. In the interface, the list of my inputs or outputs is cutted and has to be scrolled, but leaving a considerable room in interface completely empty... nothings change if i try to expand the window... lists remain the same height.
I'm on the latest win 11 release possible.... please let me know if i can help you in some way with some report if useful!

[Screenshot 2024-10-31 085712](https://github.com/user-attachments/assets/bcc1d73c-a871-4560-b0b7-bfacaaab8b46)

**Comment by ramiro-uziel** [comment]
thanks! please try this release.
https://github.com/ramiro-uziel/FlexASIO-Fluent/releases/tag/v0.2.1

**Comment by fcana** [comment]
Hi Ramiro,
yes, everything is fine also here. thank you again!
